### ISSUE TITLE
[Minespoiler] Issue: Mineweeper tweaks don't work in split messages

### ISSUE THREAD

**Issue by l0c4lh057** [l0c4lh057/BetterDiscordStuff#1]
When a game is too big to send it in one message it is splitted in multiple messages. But the tweaks (right clicking to flag as bomb, revealing all fields next to revealed zeros) only work in the first of those messages.

**Comment by CinnamonFreak** [comment]
Remove line 314

**Comment by l0c4lh057** [comment]
I already answered you on discord but to make it clear to everyone who reads this:

It is not that simple. It adds some more functionality but I do not really want to do things halfway. That is why I am not doing that. You can edit the plugin for yourself and remove the lines but I won't publish that as a fix.

**Comment by l0c4lh057** [comment]
Closing because the plugin is abandoned
