### ISSUE TITLE
ChannelTabs Issue: plugin not working, cannot open settings

### ISSUE THREAD

**Issue by VernonBoom** [l0c4lh057/BetterDiscordStuff#109]
Not only does the plugin not work at all while enabled, but it also says "Could not open settings for ChannelTabs"

1. Go to plugins, then to ChannelTabs
2. Click on settings
3. See error "Could not open settings for ChannelTabs"

I expected to be able to open the settings to fix the plugin since it wasn't working, but the settings won't even open

![error](https://user-images.githubusercontent.com/93558207/139756539-6e5e46c8-d9bc-433b-a3c8-1f45b233eb7f.jpg)

 - OS: Windows
 - Plugin Version: v2.5.6
 - Discord version: Stable
 - Compact Mode enabled? No

This only started after I updated BetterDiscord

**Comment by l0c4lh057** [comment]
I can't reproduce this, please open the console (Ctrl+Shift+I) and look for error messages.

**Comment by zLucPlayZ** [comment]
Channel Tabs wont load for me anymore. Attached to error logs.
[discord.com-1635865517084.log](https://github.com/l0c4lh057/BetterDiscordStuff/files/7461768/discord.com-1635865517084.log)
[discord.com-1635865523884.log](https://github.com/l0c4lh057/BetterDiscordStuff/files/7461769/discord.com-1635865523884.log)

**Comment by l0c4lh057** [comment]
Your config file got corrupted, you need to delete the `ChannelTabs-[something].config.json` file inside the plugins folder and then reload discord. Sadly that will remove your bookmarks and tabs.
