### ISSUE TITLE
[ChannelTabs] Issue: plugin interfering with Discord 11 theme window buttons

### ISSUE THREAD

**Issue by Jonyee04** [l0c4lh057/BetterDiscordStuff#129]
**Describe the bug**
I just installed Discord 11 theme, and for some reason the Channeltabs plugin is interfering with discord window buttons

**To Reproduce**
Just intall discord 11 theme and the channeltabs plugin

**Expected behavior**
The tabs are still there but not interfering with the Discord window buttons

**Videoshots**
before the plugin activation and after

https://user-images.githubusercontent.com/103516099/162991797-3c8b62b3-d391-4d15-a7e5-4f0b0415ae56.mp4

**Information**
 - OS: [Windows]
 - Plugin Version: [v2.6.0]
 - Discord version: [Stable]
 - Compact Mode enabled? [yes]

**Comment by Jonyee04** [comment]
i just wanted to use the canneltabs with discord 11 theme haha

**Comment by maenDisease** [comment]
Try https://github.com/l0c4lh057/BetterDiscordStuff/pull/124

**Comment by Jonyee04** [comment]
well, didnt worked, i tried to put it in theme css but nothing happened

**Comment by maenDisease** [comment]
No, it’s a pending channeltabs update, click on the changed files tab -> press the … on the right, click view file, the press the … again, press view raw, then ctrl s to save the file

**Comment by Jonyee04** [comment]
i did saved, in the css theme of course, but nothing happened,

are you talking about saving the code i put in or a new way to solve the problem? if it's a new way I didn't find it :/

**Comment by maenDisease** [comment]
You save it as a plug-in file to replace channelrabs

**Comment by Jonyee04** [comment]
i will use another theme, i cant solve this one haha

thanks anyway
