### ISSUE TITLE
[ChannelTabs]  bar is now fully transparent

### ISSUE THREAD

**Issue by 4n0nct** [l0c4lh057/BetterDiscordStuff#134]
The bar is now fully transparent, while it was sort of grey semi-transparent before, looking like my theme.

**To Reproduce**
Launching the plugin with or without css parameters (commentated)
The bar is now fully transparent, even without my css and when tweaking my theme.
The problem appeared after the last update.

**Expected behavior**
Semi transparent, respecting the custom css which was working.

**Information (please complete the following information):**
 - OS: arch
 - Plugin Version: the last one
 - Discord version: Stable
 - Compact Mode enabled? Yes and No, same thing for the two of them

**Comment by maenDisease** [comment]
Is this an issue with a theme? Can you provide a screenshot?

**Comment by 4n0nct** [comment]
Sorry I forgot to edit the title, I'm not used to github, let me adjust all that.
Title redone, here a screenshot:
![2022-05-07_08-33](https://user-images.githubusercontent.com/50212348/167242050-12a42565-00e9-425a-8672-144ef1381958.png)

**Comment by maenDisease** [comment]
You have to set custom styling for your specific theme

```css
html #channelTabs-container {
    background: var(—background-tertiary);
}
```

**Comment by maenDisease** [comment]
You can close this issue if the answer was what you were looking for. And if you’d like additional help on customizing the plug-in with custom css then visit the support server

**Comment by 4n0nct** [comment]
I've tried, it didn't work.
I'll just wait for the next update of this plugin, maybe I'm not the only one affected by this.

**Comment by 4n0nct** [comment]
Found it in the plugin itself
![image](https://user-images.githubusercontent.com/50212348/167246280-2213e2a0-a613-47bc-bdf6-fd138fe6eb9e.png)
I've commented this line, the full transparency is gone
Problem solved

**Comment by 4n0nct** [comment]
![image](https://user-images.githubusercontent.com/50212348/167246589-98733554-94cb-4d6d-a4a4-6b788c530278.png)
I also commented the padding at line 2731, now it's all like before.
I'll close.
