### ISSUE TITLE
[TypingIndicator] Indicator shown on "About Me"

### ISSUE THREAD

**Issue by SylveonBottle** [l0c4lh057/BetterDiscordStuff#138]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**
Indicator shown on "About Me"

**To Reproduce**
1. Go to 'About Me'

**Expected behavior**
No Indicator shown on "About Me"

**Screenshots**
![image](https://user-images.githubusercontent.com/17802843/174653675-b7db5412-bfc7-4c86-a85b-499e1d1656f6.png)

**Information (please complete the following information):**
 - OS: windows
 - Plugin Version: 0.5.4
 - Discord version:  Stable
 - Compact Mode enabled? no]

**Additional context**
none

**Comment by l0c4lh057** [comment]
that is not from TypingIndicator, but some plugin from @Strencher (InvisibleTyping or something like that)

**Comment by SylveonBottle** [comment]
whoops my bad, was half asleep when I made this
