### ISSUE TITLE
[Channel Tabs] Issue: when restarting discord, the tabs aren't saved

### ISSUE THREAD

**Issue by arkduquez** [l0c4lh057/BetterDiscordStuff#148]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**
When I restart the discord, all my tabs get closed.

**Expected behavior**
Usually when i closed discord and reopened it, the tabs would be just as I left then, but that's not happening anymore

**Information (please complete the following information):**
 - OS: [Windows
 - Plugin Version: [e.g. 2.6.1]
 - Discord version: [Stable,]
 - Compact Mode enabled? [yes or no]

**Comment by maenDisease** [comment]
Try opening your plugins folder, then press ALT+f4 to quit Discord, then find and delete any files containing the name ChannelTabs, then reopen Discord and see if your issue happens again.

**Comment by arkduquez** [comment]
> Try opening your plugins folder, then press ALT+f4 to quit Discord, then find and delete any files containing the name ChannelTabs, then reopen Discord and see if your issue happens again.

worked like a charm, ty
