### ISSUE TITLE
Account Switcher - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by PriceOfHell** [l0c4lh057/BetterDiscordStuff#18]
Whenever I add it to my plugins folder I get an error that says "load strings are not defined" and then cancels out all of my plugins unless I delete it. I have a business account and a personal account and this made the account switcher so easy. I've even been able to make another account just to test things out with my server and it was so convenient to have it. If you could fix this as soon as possible that would be amazing.

**Comment by l0c4lh057** [comment]
can you please open the console (ctrl+shift+i, then select the "console" tab), click the error message you get in the alert and screenshot the error message which appears in the console?

**Comment by l0c4lh057** [comment]
probably not an issue anymore, did not hear of this bug ever again
