### ISSUE TITLE
Account Switcher - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by JustAdler** [l0c4lh057/BetterDiscordStuff#22]
Downloading site does not work, it shows URL error. Have tried with multiple browsers but still.
![image](https://user-images.githubusercontent.com/55048765/64486673-94534f00-d238-11e9-9a79-bfeeee7722f1.png)

**Comment by l0c4lh057** [comment]
Download here: https://github.com/l0c4lh057/AccountSwitcher
