### ISSUE TITLE
Account Switcher - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by SamTheFamYT** [l0c4lh057/BetterDiscordStuff#23]
Invalid Link, "Server Failure"

**Comment by l0c4lh057** [comment]
Download here: https://github.com/l0c4lh057/AccountSwitcher

**Comment by SamTheFamYT** [comment]
Hey, I am having problems with the account switcher, I have put the code into "Custom CSS" and I cannot find how to do it

On 8 September 2019 at 9:48, Aaron <notifications@github.com> wrote:



Closed #23.

**Comment by l0c4lh057** [comment]
if you follow the link i sent you, you should see the readme file and at the bottom there is a download link. just click it and download to the correct directory (settings > plugins > click the "open plugin folder" button)

**Comment by SamTheFamYT** [comment]
I downloaded it and dropped it into the plugins folder and it says "file could not be constructed"

On 9 September 2019 at 11:41, Aaron <notifications@github.com> wrote:



if you follow the link i sent you, you should see the readme file and at the bottom there is a download link. just click it and download to the correct directory (settings > plugins > click the "open plugin folder" button)

**Comment by l0c4lh057** [comment]
can you please join my support server? giving support there will be a bit easier i think
https://l0c4lh057.jg-p.eu/discord.html
