### ISSUE TITLE
[Typing Indicator] Issue: Doesn't display on guilds

### ISSUE THREAD

**Issue by RisingChops** [l0c4lh057/BetterDiscordStuff#25]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**
When someone types in a server chat it shows next to the channel like it should but it doesn't show up on the guild icons like it did before the newest discord update

**To Reproduce**

**Expected behavior**

**Screenshots**
Please also check the console by pressing `Ctrl + Shift + I` and send screenshots of errors (red messages)

**Information (please complete the following information):**
 - OS: Windows 10
 - Plugin Version: 0.2.1
 - Discord version: Stable
 - Compact Mode enabled? no

**Additional context**

**Comment by l0c4lh057** [comment]
fixed in 528f88b
