### ISSUE TITLE
[Account Switcher] Issue: Pressing settings doesn't work

### ISSUE THREAD

**Issue by EpicKitty666** [l0c4lh057/BetterDiscordStuff#3]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**
Basically, in the BandagedBD version, in the plugin menu, clicking on settings while the plugin is on, makes all other plugins disappear from the menu including this one, and they reappear once the tab is reopened.

**To Reproduce**
1. Go to User Settings>Plugins in discord
2. Click on settings under the Account Switcher
3. All plugins disappear and the settings menu doesn't open.

**Expected behavior**
I expected the settings menu or dialogue to open.

**Screenshots**
![image](https://user-images.githubusercontent.com/47422728/54475202-9509ac00-47e6-11e9-9e42-c1cbf709d5c3.png)

**Information (please complete the following information):**
 - OS: Win 10 Home
 - Plugin Version: 0.0.1
 - Discord version: Stable
 - Compact Mode enabled? no

**Comment by l0c4lh057** [comment]
Verison 0.0.1 was the first release, it had no auto updater in it. Please update to the [newest version](https://github.com/l0c4lh057/BetterDiscordStuff/blob/master/Plugins/AccountSwitcher/AccountSwitcher.plugin.js), that should be working. (Even though idk what could cause this in 0.0.1)

**Comment by l0c4lh057** [comment]
Please give me feedback about if it works now or if it doesn't, otherwise I will close this thread.
