### ISSUE TITLE
Minesweeper dosent work

### ISSUE THREAD

**Issue by theparaodxdoge** [l0c4lh057/BetterDiscordStuff#33]
Well. It dosent work lol

**Comment by MinerChAI** [comment]
Provide more information

**Comment by theparaodxdoge** [comment]
I type the command. Nothing happens

**Comment by l0c4lh057** [comment]
tthere was an update in 34ada00 that should have fixed this issue. please tell me if it is working after updating

**Comment by theparaodxdoge** [comment]
It worked. Thanks 😊

Sent from Mail for Windows 10
