### ISSUE TITLE
Minesweeper is broken

### ISSUE THREAD

**Issue by Mirrored6** [l0c4lh057/BetterDiscordStuff#36]
if i click the box and it is a zero it doesn't do the whole field and when i hit a bomb it also doesn't clear the whole field
![image](https://user-images.githubusercontent.com/47297746/73739371-6110df80-4746-11ea-97b7-15d2450f3084.png)

**Comment by l0c4lh057** [comment]
Blame @1Lighty for all the time the update is not out after 2 pm CET. he's not answering my question on how to do something so the update is still waiting. this special part has been fixed but i want to completely fix the plugin before updating it
