### ISSUE TITLE
[TypingIndicator] Request: Prevent the typing indicator icon from appearing when you are the only one typing

### ISSUE THREAD

**Issue by littlebroto1** [l0c4lh057/BetterDiscordStuff#40]
**Is your feature request related to a problem? Please describe.**
I find it annoying that whenever I start typing within a channel and switch to a different channel the typing indicator appears on the channel I was just typing in, even if nobody else started typing.

**Describe the solution you'd like**
I can imagine that a simple solution might be to add an if check to see if the person typing is the current user.

**Additional context**
I don't have a screen recorder to show the problem related to this feature request, but it should be simple to test by going to a channel, typing a few words, then going to another channel.

**Comment by l0c4lh057** [comment]
added in 05e2dd2
