### ISSUE TITLE
[TypingIndicator] Issue: Doesn't work on Home Icon

### ISSUE THREAD

**Issue by RisingChops** [l0c4lh057/BetterDiscordStuff#41]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**
Typing Indicator doesn't work for the Home Icon

**To Reproduce**
Have someone try messaging you

**Expected behavior**
Typing Indicator to show on Home Icon but it doesn't

**Screenshots**
Please also check the console by pressing `Ctrl + Shift + I` and send screenshots of errors (red messages)

**Information (please complete the following information):**
 - OS: Windows 10
 - Discord version: Stable
 - Compact Mode enabled? [no]

**Additional context**

**Comment by l0c4lh057** [comment]
Fixed in aae56a2
