### ISSUE TITLE
[GuildData] Issue: Export members and role list no longer functions

### ISSUE THREAD

**Issue by ghost** [l0c4lh057/BetterDiscordStuff#45]
**Describe the bug**
Exporting a list of all members or all roles from a guild opens up a save location window, but doesn't seem to actually save the file or some reason. The file is not "hidden", it just doesn't do anything. Not sure what the issue is, but it was worked before and was very useful.

**Information (please complete the following information):**
 - OS: [e.g. Linux Mint 19]
 - Plugin Version: [2.0.7]
 - Discord version: [Stable and Snap]
 - Compact Mode enabled? [no]

**Additional context**
It worked before, it's a shame it doesn't work now. I would be willing to use an earlier version of GuildData if I was assured this function would work. I assume the bug is due to changes Discord made.

**Comment by l0c4lh057** [comment]
Closing because the plugin is abandoned
