### ISSUE TITLE
[ChannelTabs] Request: Have Background be transparent for custom backgrounds.

### ISSUE THREAD

**Issue by Sportiax** [l0c4lh057/BetterDiscordStuff#46]
The plugin currently has the background set for dark mode, giving a gray background, this is a bit of an eyesore with the custom theme I have. I just recommend having the background set to be transparent to be compatible with any user's theme.

**Comment by l0c4lh057** [comment]
The background is set to a default discord variable. If the theme just changes the variables it will also support this plugin but if the theme just changes the colors of the individual elements then it does not theme this plugin.

**Comment by Sportiax** [comment]
> The background is set to a default discord variable. If the theme just changes the variables it will also support this plugin but if the theme just changes the colors of the individual elements then it does not theme this plugin.

I see, thanks for letting me know. I was able to change it with my custom theme settings. Didn't realize I still had some options/values set to Discord's default.
