### ISSUE TITLE
[ChannelTabs] Request: Icon for groups

### ISSUE THREAD

**Issue by GE0NE** [l0c4lh057/BetterDiscordStuff#50]
The newest update added icons in the tabs for DMs and servers, but not for groups DMs with custom icons.
It would be nice if this feature was added too for consistency

**Comment by l0c4lh057** [comment]
It will be included soon, I just did not see the image url of a DM group rn. I'll take a look again and then add it.

**Comment by l0c4lh057** [comment]
Was not pretty soon, but it was added recently
