### ISSUE TITLE
[ChannelTabs] Issue: Tab Overlap on Title Bar Buttons

### ISSUE THREAD

**Issue by vBread** [l0c4lh057/BetterDiscordStuff#51]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**
Visual overlap occurs when focused on the Discord client, doesn't appear if unfocused

**To Reproduce**
Enable ChannelTabs and stay in the current window

**Expected behavior**
Push tabs to the right

**Screenshots**
Please also check the console by pressing `Ctrl + Shift + I` and send screenshots of errors (red messages)

![Screen Shot 2020-08-19 at 9 36 33 PM](https://user-images.githubusercontent.com/60681223/90706917-53472580-e264-11ea-83b8-490853d40acb.png)
Focused

![Screen Shot 2020-08-19 at 9 37 06 PM](https://user-images.githubusercontent.com/60681223/90706929-59d59d00-e264-11ea-9c21-78ac1ba84f45.png)
Not Focused

**Information (please complete the following information):**
 - OS: MacOS
 - Plugin Version: [e.g. 1.1.1]
 - Discord version: Stable
 - Compact Mode enabled? No

**Additional context**

**Comment by l0c4lh057** [comment]
Fixed in ed4347e...f2d736c

**Comment by zipherfox** [comment]
> Fixed in [ed4347e...f2d736c](https://github.com/aarondoet/BetterDiscordStuff/compare/ed4347e741c6f3c88dcafcd6c7c0524b9d71dbd3...f2d736c67f29ecc69a39e1ba4883a06aaee9e3b1)

If my theme does modify those window control button is there anything I can do to fix it so that it won't overlapping each other?
