### ISSUE TITLE
[PluginName] Issue: Conflict with GameActivityToggle

### ISSUE THREAD

**Issue by mohcow** [l0c4lh057/BetterDiscordStuff#52]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**
When using ChannelTabs and GameActivityToggle the button of GameActivityToggle vanishes.

**To Reproduce**
Steps to reproduce the behaviour:
1. While ChannelTabs + GameActivityToggle is enable at startup and the button that GameActivityToggle creates disappears
2. After restarting GameActivityToggle while ChannelTabs is running the button stays and both plugins work fine
3. After restarting ChannelTabs while GameActivityToggle is running the button disappears again.

**Expected behaviour**
Both plugin should work side by side

**Screenshots**
Please also check the console by pressing `Ctrl + Shift + I` and send screenshots of errors (red messages)

**Information (please complete the following information):**
 - OS: Windows
 - Plugin Version: ChannelTabs 1.2.0 GameActivityToggle 1.2.6 https://github.com/Egrodo/DiscordPlugins/blob/master/GameActivityToggle.plugin.js
 - Discord version: Stable
 - Compact Mode enabled? no

**Comment by Juby210** [comment]
Game activity toggle is really bad typed, probably localhost has nothing to do with it. I suggest you to ask egrodo to remake his plugin like me for powercord: https://github.com/Juby210/game-activity-toggle

**Comment by l0c4lh057** [comment]
It could be that I was actually causing this but if that actually was the case this should no longer be a problem. Either it is no problem anymore or it is nothing I am causing, so I'll just close this issue.
