### ISSUE TITLE
[GuildData] Issue: Role filter missing

### ISSUE THREAD

**Issue by tacusin** [l0c4lh057/BetterDiscordStuff#54]
Used to be able to click on one of the roles in the Role Information section to get a filtered list of users assigned to that role. The latest updates seem to be missing this. Is that intentional or not?

 - OS: [Windows]
 - Plugin Version: [e.g. 2.0.8]
 - Discord version: [Stable]
 - Compact Mode enabled? [no]

**Comment by l0c4lh057** [comment]
Closing because the plugin is abandoned
