### ISSUE TITLE
[ChannelTabs] Excessive blank space

### ISSUE THREAD

**Issue by minhngoc25a** [l0c4lh057/BetterDiscordStuff#57]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**
There is a blank space below the ChannelTabs

**To Reproduce**
Restarting Discord does not work. Shows up everytime I launch Discord.

**Screenshots**
Please also check the console by pressing `Ctrl + Shift + I` and send screenshots of errors (red messages)
![image](https://user-images.githubusercontent.com/33834488/94401335-a8942200-0194-11eb-951c-74c5f29cfe36.png)

**Information (please complete the following information):**
 - OS: [e.g. Windows, MacOS, TempleOS] Windows 10
 - Plugin Version: [e.g. 1.2.3]v2.0.3 
 - Discord version: [PTB, Stable, Canary] Stable
 - Compact Mode enabled? [yes or no] No

**Additional context**

**Comment by l0c4lh057** [comment]
The change log exactly tells you why that is. There is a new feature, you can set bookmarks and that is the bar in which they show up. It also tells you that you can disable it in the settings if you don't want to use that feature.
