### ISSUE TITLE
[Channel Tabs] Request: Indicator on active favorite

### ISSUE THREAD

**Issue by Vaelek** [l0c4lh057/BetterDiscordStuff#63]
I really don't use the actual tabs, I hate that they can't be pinned and just keep changing as you select different rooms, so I exclusively use the favorites. Since you're going HAM on updates right now, I'd like to request a way to have an indicator of some sort that signifies that a favorite is the currently active room. Even if it just means adding a classname to it that I can run with via customCSS. TIA!

**Comment by l0c4lh057** [comment]
added more classes to bookmarks in 9ba0854
