### ISSUE TITLE
[ChannelTabs] MacOS window not draggable with extension installed

### ISSUE THREAD

**Issue by Carcraftz** [l0c4lh057/BetterDiscordStuff#64]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**
When using macOS, the discord window is not draggable (the window does not move when you try to drag it around, meaning discord is fixed in one spot on your screen

**To Reproduce**
1. Go to the discord app on mac with the plugin installed
2. Try dragging around the window

**Expected behavior**
The window drags around like any mac app

**How to fix**

In order to fix this issue, this style needs to be added to the div that the plugin adds to manage the tabs, so that the top bar is draggable.  
-webkit-app-region: drag

**Information (please complete the following information):**
MacOS
No compact mode
Discord Stable
v2.3.2 of plugin

**Comment by l0c4lh057** [comment]
Feel free to make a PR and I'll merge it. (a Mac specific selector please!)
Otherwise I'll update it on the weekend.

**Comment by l0c4lh057** [comment]
should be fixed in 9ba0854
