### ISSUE TITLE
[TypingIndicator] Request: Log to the .json file who, and on which channel is typing.

### ISSUE THREAD

**Issue by MichalD96** [l0c4lh057/BetterDiscordStuff#66]
TypingIndicator should have a setting to log to the file who, on what channel and when was typing.
User should be able to specify on what servers and channels this feature should work. Would be nice to have output in `.json` file like this:

```json
[
    { "server": "<serverName>", "timeStamp": "2020-11-05T14:48:00.000Z", "user": "<userName>" }
]
```
If it is possible it should log only the typing events when user didn't send the message for over for example 1 min.

**Comment by l0c4lh057** [comment]
Feel free to do that yourself but imo that is
1. logging user metadata which I don't want to do, and it might even be against the betterdiscord terms
2. just a waste of storage space. over time the log would just grow and grow.
