### ISSUE TITLE
[Minespoiler] the last phew boxes

### ISSUE THREAD

**Issue by The-Helmet-YT** [l0c4lh057/BetterDiscordStuff#68]
On the desktop discord, the last 2 boxes of each message are not shown and on mobile, the last box (bottom right) is not tappable.

**Comment by l0c4lh057** [comment]
Discord only allows a certain amount of spoilers in a message but i thought i already made the limit low enough, guess i was wrong

**Comment by l0c4lh057** [comment]
Closing because the plugin is abandoned
