### ISSUE TITLE
Minespoiler Issue: Flagging feature and automatic reveal not working

### ISSUE THREAD

**Issue by jenduis** [l0c4lh057/BetterDiscordStuff#69]
Flagging feature when you right click and the automatic reveal when you lose only works when game sent a channel with no previous messages. Otherwise failing doesnt work and you need to click all zeroes one by one.

![image](https://user-images.githubusercontent.com/66085054/101008683-d6ba2780-3572-11eb-98af-acba23f23dff.png)
![image](https://user-images.githubusercontent.com/66085054/101008985-ee91ab80-3572-11eb-889e-ab7cb8d49a85.png)

**Comment by l0c4lh057** [comment]
Closing because the plugin is abandoned
