### ISSUE TITLE
[TypingIndicator] Issue: You can't see when a person is writing in a channel.

### ISSUE THREAD

**Issue by JpPgn612** [l0c4lh057/BetterDiscordStuff#70]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**
Even if the plugin is enabled, you can't see when a person is typing in a channel. The three points doesn't show, even when you restart discord. And you can't enable the other options, like "Include muted channels/guilds"; "Show on Guilds" etc... It's like the option is blocked on disabled.

1. Go to Plugins
2. Go to TypingIndicator
3. Try to enable other settings, like "Include blocked users" or "Show on guilds"
4. See the error
5. Go to any server and watch the channel list
6. See the error again.

**Expected behavior**
The three points shows again when a person's writing inside a channel (or many people that are typing in a channel) and the possibility to enable more options of the plugin.

**Screenshots**
https://user-images.githubusercontent.com/76466840/102856829-81fa2600-4427-11eb-97db-6f27859e2f2b.mp4

**Information (please complete the following information):**
 - OS: Windows 10
 - Plugin Version: 0.4.3
 - Discord version: Stable
 - Compact Mode enabled? No

**Comment by l0c4lh057** [comment]
For the toggles in the settings not working: you are probably one of the few who updated ZeresPluginLibrary within the first hour. Redownload it and then the toggles should work.

For the indicator not working on channels: I know. But somehow the react dev tools won't get added to discord and without them it is no fun to fix. At some point I will fix it but that is why it will be a bit later than I usually fix bugs.

**Comment by SkyEmie** [comment]
Good luck to fix it, you have many users who use ur script😄

**Comment by l0c4lh057** [comment]
Fixed in 483619e
