### ISSUE TITLE
[TypingIndicator] Request: Show avatar of users typing next to the typing gif

### ISSUE THREAD

**Issue by Alonely0** [l0c4lh057/BetterDiscordStuff#73]
I'd like to see who's writing in the channel.

The most efficient form is to show the avatars at the left of the typing gif.
But also, you could implement seeing the users typing by hovering the channel with the mouse.
Anyway, those two methods could be implemented, you could see the avatar next to the typing gif, and the name if you hover the channel

![image](https://user-images.githubusercontent.com/59423215/104502583-b7d29a80-55e0-11eb-8e47-85f7c318be1c.png)

**Comment by l0c4lh057** [comment]
I already thought about something like this but decided not to do it because the plugin only knows the user ID of those typing, not the username or anything like that. You can look users up by their ID but they might not be cached which means you can't retain any information about them. But yeah, I might add that. I'd rather add a tooltip tho.  
I can imagine it like
- `person1#1234` if one person is typing that is cached
- `person1#1234, person2#6789` if two people are typing that are cached
- `person1#1234 and 3 others` if at least 3 people are typing and at least one of them is cached
- `2 people` if none of the users are cached

I don't want to make the tooltips too long so only 1 person, 2 people or 1 person and the amount of others will show.

**Comment by Alonely0** [comment]
> the plugin only knows the user ID of those typing

I developed discord bots ins the past, and you can get avatars, usernames, etc with the ID.

> but they might not be cached

For caching them you could save all the IDs in an array. Then you should make a for loop that saves into another array the URL of the avatars and then pass it to the frontend.

> I can imagine it like...

Nah, I prefer avatars, and a hover tooltip with the username.

**Comment by Strencher** [comment]
> For caching them you could save all the IDs in an array. Then you should make a for loop that saves into another array the URL of the avatars and then pass it to the frontend.

But if they are not cached you only have a userId, and that's all. Fetching them would spam the api.

**Comment by l0c4lh057** [comment]
> I developed discord bots ins the past, and you can get avatars, usernames, etc with the ID.

I just checked and the [bot api docs seem to also say this](https://discord.com/developers/docs/topics/gateway#typing-start) (even tho that also only works for guilds, not for DMs) but when subscribing in the client this information does not seem to be sent.
![grafik](https://user-images.githubusercontent.com/42084688/104839610-7da81800-58c2-11eb-9f0f-d369691074c4.png)
Also not everything a bot library allows you to do is what the api actually allows. Most libraries have a cache with every member in it and allow you to just access the member object of an event when in fact you only have the user id provided by the event. Also the bot API is partially different to the user API, even if they are the same most of the time.

> For caching them you could save all the IDs in an array. Then you should make a for loop that saves into another array the URL of the avatars and then pass it to the frontend.

You can't just get the avatar URL by the user id. You'd need to request the member/user for every id that is not cached and afaik you can't even bulk request them. (You can bulk request members but I don't think you can request a specific set of members by their id in one request)

> Nah, I prefer avatars, and a hover tooltip with the username.

Feel free to make your own fork and add the avatars. A missing cache is one reason why I don't like that idea and that this able to take a lot of space, depending on how active the channel is, might blocking most of the channel name especially if it already is pretty long, that is why I would not do it like that.

**Comment by l0c4lh057** [comment]
I added a tooltip in 00ef1a2 and I won't add avatars for reasons explained above.
