### ISSUE TITLE
[MineSpoiler] Issue: MineSpoiler Could Not Be Started

### ISSUE THREAD

**Issue by a7md8762** [l0c4lh057/BetterDiscordStuff#79]
When I Try To Enable MineSpoiler Plugin it Says "MineSpoiler Could Not Be Started"

![Screenshot_20210405_101404](https://user-images.githubusercontent.com/81858682/113553807-99d17080-95f8-11eb-8b12-172f9eeb72f5.png)

So If Anyone Know How to Enable It Please Tell Me.

( Some Information May Help )

Discord Version: Stable
Plugin Version: 1.0.10

**Comment by NathanTurnYT** [comment]
I also have the same problem.

**Comment by cfpwastaken** [comment]
Same problem here

**Comment by QuantumWarpCode** [comment]
Anyone know how to get debug info on this for the dev?

**Comment by l0c4lh057** [comment]
No need to, the plugin is discontinued, at least for now. I won't fix it any time soon.

**Comment by l0c4lh057** [comment]
Closing because the plugin is abandoned
