### ISSUE TITLE
[Minespoiler] Issue: When I try to start the plugin, the following message "Minespoiler could not be started" appears. What do I do? Thanks.

### ISSUE THREAD

**Issue by pedrogiroto7** [l0c4lh057/BetterDiscordStuff#80]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Please also check the console by pressing `Ctrl + Shift + I` and send screenshots of errors (red messages)

**Information (please complete the following information):**
 - OS: [e.g. Windows, MacOS, TempleOS]
 - Plugin Version: [e.g. 1.2.3]
 - Discord version: [PTB, Stable, Canary]
 - Compact Mode enabled? [yes or no]

**Additional context**

**Comment by l0c4lh057** [comment]
Yes, the plugin is broken. And it will probably not get fixed, I'm sorry about that.
