### ISSUE TITLE
[ChannelTabs] Doesn't work after Discord's broken update (doesn't construct)

### ISSUE THREAD

**Issue by HRudyPlayZ** [l0c4lh057/BetterDiscordStuff#82]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**
The plugin was broken by the stupid update that happened recently to Discord (the same one that brought back the gif crashes)

**To Reproduce**
1. Update Discord
2. The plugin won't work anymore and will throw an error at boot.

**Expected behavior**
The plugin should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/29356467/116599434-626c9000-a928-11eb-8916-93f91159ecaf.png)

**Information (please complete the following information):**
 - OS: Windows
 - Plugin Version: 2.4.1
 - Discord version: Stable, latest
 - Compact Mode enabled? no

**Comment by duendwang** [comment]
Same thing happens to me. Downloading the updated one from github is broken, but using the one I had before works (I needed to delete the config file). The one I had before was 2.4.1 (not sure what the one I downloaded from github is).

**Comment by mkcoldwolf** [comment]
Lmao turns out its because of the update somehow corrupted the config.json, delete ur `ChannelTabs.config.json` it works fine again
![image](https://user-images.githubusercontent.com/32544898/121801372-90542c80-cc69-11eb-9aa4-0ec999ace2b7.png)
