### ISSUE TITLE
[Typingindicator] Issue: crash when clicked

### ISSUE THREAD

**Issue by nexioss** [l0c4lh057/BetterDiscordStuff#89]
**Describe the bug**
when someon is tiping on the chat and click on the pfp discord just chow a error and need to restart

**To Reproduce**
1.someon tiping on chat
2. Click on the pfp to the botom of the text bar

**Expected behavior**
do nothing, or chow the user profile

**Screenshots**

https://user-images.githubusercontent.com/86494178/123563044-a65a0500-d7b2-11eb-92fc-b2299dd01ea8.mp4

**Information**
 - OS: wndows 10 21H1
 - 0.5.2
 - Stable 88863 (957df89)
 - Compact Mode disabled

**Additional context**
none

**Comment by l0c4lh057** [comment]
TypingIndicator does not mess with that at all, it only adds indicators were none exists, it does not modify already existing ones. I guess you'll need to ask @QWERTxD about this, probably Typing Users Avatars causing this.

**Comment by nexioss** [comment]
the existing one have no pfp and just the pseudo. its only occure when whe click on the pfp

**Comment by nexioss** [comment]
oh.. sorry u just forget this is not on the same plugin
