### ISSUE TITLE
[TypingIndicator] Request: Stop animation when unfocussed

### ISSUE THREAD

**Issue by Nymfya** [l0c4lh057/BetterDiscordStuff#9]
This plugin is good but he have a smallest "problem".

Plugin is always doing animation when discord is unfocussed

I don't know if you can detect this but if you can this can be really cool if you can disable animation when discord is unfocussed

yeah is very a smallest problem but on poor PC or when games is started is takes performance for nothing.

(sry if my english is poor)

**Comment by l0c4lh057** [comment]
I'll look into that and maybe add this when I find out how, thanks for the suggestion.

**Comment by l0c4lh057** [comment]
I tried adding this in 00ef1a2 but it seems like it does not always stop the animation. I don't know why so I will further look into that and hopefully fix that. As long as this issue is not resolved I will keep this open.

**Comment by l0c4lh057** [comment]
Well it seems to work now. Idk if it was d2a4a44 but I doubt that changed anything. Anyways, it seems to be fine now.
